### ISSUE TITLE
[V11] l10n_nl_tax_statement: Update of past undeclared invoices - Update of BTW statement doesn't work 

### ISSUE THREAD

**Issue by tv-openbig** [OCA/l10n-netherlands#219]
Hello,

i have just checked the V11 version of l10n_nl_tax_statement in order to adopt it for the german "clone" of this module: https://github.com/openbig/l10n-germany/tree/10.0/l10n_de_tax_statement.

I have created a customer invoice with the tax "Verkopen/omzet hoog" with a invoice date in between of the given date_range in the tax statement. If i click on update button the value in the line "1a Leveringen/diensten belast met hoog tarief"  was calculated correctly.

Now i created two further invoices with a invoice date before the "from_date" of the statement. If i go to the tab "Past undeclared invoices" i can see the two lines. Now i wanted to include those lines in the statement by clicking on the ">" arrow to add them + clicking on the "update" button as suggested by the description "Add/Remove the Undeclared Invoices listed below. Afterwards press the Update button in order to recompute the statement lines!".

<img width="831" alt="bildschirmfoto 2019-02-08 um 10 20 50" src="https://user-images.githubusercontent.com/8348598/52469267-49cb0080-2b8b-11e9-95c2-abf7cb6c92e7.png">

Now i would normally expect that the line "1a Leveringen/diensten belast met hoog tarief" would have been updated but it doesn't.

<img width="917" alt="bildschirmfoto 2019-02-08 um 10 22 05" src="https://user-images.githubusercontent.com/8348598/52469333-6a935600-2b8b-11e9-9873-a1f3308e0f01.png">

Unfortunately it just shows the "regular" invoice in between of the given date range. I miss here the two further added invoices from the past months.

<img width="1015" alt="bildschirmfoto 2019-02-08 um 10 22 35" src="https://user-images.githubusercontent.com/8348598/52469364-81d24380-2b8b-11e9-8186-7ad71ec947c2.png">

Nevertheless, thanks a lot for your great work on that module. The added feature "past undeclared invoices" is a great further improvement. I will now try to adopt the V11 changes for the german accounting plans.

Best regards
Thorsten

**Comment by astirpe** [comment]
@tv-openbig Thank you for reporting this issue!
I published a fix in https://github.com/OCA/l10n-netherlands/pull/220, would you give it a try?

**Comment by tv-openbig** [comment]
@astirpe Thanks for your quick intervention.
I have checked you fix. It is nearly fixed (50%).
The omzet and btw in the list was updated as they should !

<img width="851" alt="bildschirmfoto 2019-02-08 um 15 30 58" src="https://user-images.githubusercontent.com/8348598/52484510-cd4e1700-2bb6-11e9-95cd-f0c40c3d1ded.png">

If i click on the lense to see the invoices behind i would expect to see the
"regular" invoice from the given date range + the invoice from the past.
If i open the lense of the line "1a Leveringen/diensten belast met hoog tarief" 
i get just the regular invoice, not the invoice from the past.

<img width="1010" alt="bildschirmfoto 2019-02-08 um 15 31 15" src="https://user-images.githubusercontent.com/8348598/52484662-32097180-2bb7-11e9-9edf-ed25fb4111a8.png">

Anyway big thank you so far.

**Comment by astirpe** [comment]
@tv-openbig right, I will fix it next week. Thanks!
Would you keep Onestein in the list of the authors when you clone this module?

**Comment by tv-openbig** [comment]
@astirpe 

Hello, yes sure i will. 

For the V11 version i plan a PR towards OCA/l10n-germany project. So far it was was not possible as Odoo rejected my PR to the V10 german accounting plan (https://github.com/odoo/odoo/issues/18571#issuecomment-343188141).

For the V11 we do not have anymore missing tax tags, so i am positive for the V11 PR. 
I will update the authors lists for V11 and also for the V10 "clone". 
I mentioned you already as a contributor in the README but for sure i will complete it, 
if i am ready with the V11, and for sure the "author" entry in the manifest is more relevant 
as the readme ;-)

**Comment by astirpe** [comment]
@tv-openbig Should be working fine now. Could you check?

**Comment by tv-openbig** [comment]
@astirpe in the list of journal items i still don't get the invoice lines from the past.
I have tested on this runbot instance http://3357967-220-05ec37.runbot3.odoo-community.org/?db=3357967-220-05ec37-all.
Best regards
Thorsten

**Comment by astirpe** [comment]
@tv-openbig It's because you didn't set the Country to Netherlands in _YourCompany_. The report works fine when the Country is Netherlands for the actual company.
I can understand that there is a strange behavior when the country is not set properly and that could be confusing. But the report is meant for Dutch only companies. There is space for future improvement to avoid confusions, but I don't want to spend time on it right now, since it's not part of the issue you opened and is a low prio for me.
Thanks!

**Comment by tv-openbig** [comment]
@astirpe OK, that is indeed not a big issue in that case;-)

**Comment by astirpe** [comment]
@tv-openbig in https://github.com/OCA/l10n-netherlands/pull/220 I just committed a fix for getting the invoice lines from the past when the Country is not set to Netherlands. Thanks!
